### ISSUE TITLE
unclear about the reference paper for "ALIAS difficult" sublibrary

### ISSUE THREAD

**Issue by Satinelamp** [sielemann/AlgebraTestSuite#1]
Where could I download this reference paper?
![Snipaste_2021-03-07_11-56-11](https://user-images.githubusercontent.com/62006565/110228438-262a3e00-7f3c-11eb-88af-cc118e930d9a.jpg)

**Comment by thorade** [comment]
From the ReadMe, you can find the full PhD-thesis PDF, and in that PDF, there is a citation for Merlet, pointing to this page:
http://www-sop.inria.fr/coprin/logiciels/ALIAS/Benches/benches.html
